### ISSUE TITLE
Phoenix 1.3 compatible?

### ISSUE THREAD

**Issue by gaynetdinov** [deadtrickster/prometheus-phoenix#3]
Currently phoenix dependency is locked on 1.2 branch. Is `promeheus-phoenix` compatible with phoenix 1.3?

**Comment by deadtrickster** [comment]
AFAIK instrumentation API hasn't changed. I'm still waiting for stable release. Are you using it already?

**Comment by gaynetdinov** [comment]
Kind of, I started to upgrade one of our projects to 1.3 version. Today I tested it on staging and it seems everything is okay, graphs are still there. I had to put `override: true` for `phoenix` dependency.

**Comment by deadtrickster** [comment]
Just pushed new version. Also added view instrumentation.
